/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.librarymanagementsystem;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;


/**
 *
 * @author yan
 */
public class BookReturnWindow extends javax.swing.JFrame {

    /**
     * Creates new form BookReturnWindow
     */
    public BookReturnWindow() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dark_Return.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 250, 80));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dark_Back.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 200, 80));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 460, 32));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG_BookReturnWindow.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DASHBOARD dash = new DASHBOARD();
        setVisible(false);
        dash.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        copyBookTitleToReturnedFile();
        updateBookReturn();
        deleteBookOnBorrowed();
        //deleteMember();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void updateBookReturn(){
        String searchTitle = jTextField1.getText().trim();
        String bookTitle = null;
        String memberName = null;
        String dateTime = null;
        String memberFile = "ManageMember.txt";
        boolean memberFound = false;
        if (searchTitle.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the book title.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try (BufferedReader reader = new BufferedReader(new FileReader(memberFile));
             BufferedWriter writer = new BufferedWriter(new FileWriter(memberFile, true))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(","); // Assuming the file is comma-separated
                String titleCheck = parts[1].trim(); // Extract the book title (first part of the line)

                if (titleCheck.equalsIgnoreCase(searchTitle)) { // Match found
                    memberFound = true;
                    bookTitle = parts[1];
                    memberName = parts[0];
                    dateTime = parts[2];
                    reader.close();
                    writer.close();
                    break;
                }
            }

            if (memberFound) {
                deleteMember();
                // Write member name to MembersList.txt
                try (BufferedWriter memberWriter = new BufferedWriter(new FileWriter(memberFile, true))) {
                    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
                    LocalDateTime dateTimeNow = LocalDateTime.now();
                    memberWriter.write(memberName + "," + bookTitle + "," + dateTime + "," + dateTimeNow.format(formatter)); // Write the member name to the file
                    memberWriter.newLine();
                } catch (IOException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, 
                            "An error occurred while saving the member name: " + e.getMessage(), 
                            "Error", 
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                        "Book not found: " + searchTitle, 
                        "Not Found", 
                        javax.swing.JOptionPane.WARNING_MESSAGE);
            }

        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "An error occurred: " + e.getMessage(), 
                    "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    
    }
    private void deleteBookOnBorrowed(){
        String bookTitle = jTextField1.getText().trim();
        if (bookTitle.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the book title.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        File originalFile = new File("Borrowed.txt");
        File tempFile = new File("books_temp.txt");

        boolean isRemoved = false;

        try (BufferedReader reader = new BufferedReader(new FileReader(originalFile));
             BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))) {

            String line;
            while ((line = reader.readLine()) != null) {
                // Check if the line contains the book ID
                if (line.contains(bookTitle)) {
                    isRemoved = true; // Mark as removed
                    continue; // Skip writing this line to the temp file
                }
                writer.write(line);
                writer.newLine();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error processing file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
         // Replace the original file with the temp file
        if (isRemoved) {
            if (originalFile.delete()) {
                tempFile.renameTo(originalFile);
                JOptionPane.showMessageDialog(this, "Book returned successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error updating the file.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            tempFile.delete(); // Cleanup temp file
            JOptionPane.showMessageDialog(this, bookTitle + " is not found in the library.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void deleteMember(){
        String bookId = jTextField1.getText().trim(); // Get the input from the text field

        if (bookId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a book title.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        File originalFile = new File("ManageMember.txt");
        File tempFile = new File("books_temp.txt");

        boolean isRemoved = false;

        try (BufferedReader reader = new BufferedReader(new FileReader(originalFile));
             BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))) {

            String line;
            while ((line = reader.readLine()) != null) {
                // Check if the line contains the book ID
                if (line.contains(bookId)) {
                    isRemoved = true; // Mark as removed
                    continue; // Skip writing this line to the temp file
                }
                writer.write(line);
                writer.newLine();
                
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error processing file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
         // Replace the original file with the temp file
        if (isRemoved) {
            
            if (originalFile.delete()) {
                tempFile.renameTo(originalFile);
            } 
        } else {
            tempFile.delete(); // Cleanup temp file
        }
    }
    public void copyBookTitleToReturnedFile() {
        String bookTitle = jTextField1.getText().trim();

        if (bookTitle.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the book title.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        BufferedReader reader = null;
        BufferedWriter writer = null;
        BufferedWriter tempWriter = null;
        File tempFile = new File("temp.txt");

        try {
            reader = new BufferedReader(new FileReader("ManageBorrowed.txt"));
            writer = new BufferedWriter(new FileWriter("ManageReturned.txt", true));  // Append mode
            tempWriter = new BufferedWriter(new FileWriter(tempFile));

            String line;
            boolean bookFound = false;

            // Read each line from borrowed.txt
            while ((line = reader.readLine()) != null) {
                if (line.equalsIgnoreCase(bookTitle)) {
                    writer.write(line);  // Write the book title to returned.txt
                    writer.newLine();
                    bookFound = true;
                } else {
                    tempWriter.write(line);  // Keep other books in temp.txt
                    tempWriter.newLine();
                }
            }
            
            if (bookFound) {
                JOptionPane.showMessageDialog(this, "Book returned: " + bookTitle, "Success", JOptionPane.INFORMATION_MESSAGE);
                // Replace borrowed.txt with the updated temp file
                tempFile.renameTo(new File("ManageBorrowed.txt"));
            } else {
                JOptionPane.showMessageDialog(this, "The entered book title was not found in borrowed.txt.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error accessing files: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (reader != null) reader.close();
                if (writer != null) writer.close();
                if (tempWriter != null) tempWriter.close();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error closing files: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookReturnWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookReturnWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookReturnWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookReturnWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookReturnWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
