/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.librarymanagementsystem;

/**
 *
 * @author User
 */
public class DASHBOARD extends javax.swing.JFrame {

    /**
     * Creates new form DASHBOARD
     */
    public DASHBOARD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        AddRemove = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        BorrowReturn = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        Manage = new javax.swing.JButton();
        AvailBooks = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Light_AddRemove.png"))); // NOI18N
        AddRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(AddRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 150, 107));

        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Light_Search.png"))); // NOI18N
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 150, 107));

        BorrowReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Light_IssueReturn.png"))); // NOI18N
        BorrowReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowReturnActionPerformed(evt);
            }
        });
        getContentPane().add(BorrowReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 150, 107));

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Light_LogOut.png"))); // NOI18N
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 150, 107));

        Manage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Light_ManageMembers.png"))); // NOI18N
        Manage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageActionPerformed(evt);
            }
        });
        getContentPane().add(Manage, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 150, 107));

        AvailBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Light_ViewBooks.png"))); // NOI18N
        AvailBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvailBooksActionPerformed(evt);
            }
        });
        getContentPane().add(AvailBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 150, 107));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dashboard.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageActionPerformed
        // TODO add your handling code here:
        ManageMembersWindow manageWindow = new ManageMembersWindow();
        setVisible(false);
        manageWindow.setVisible(true);
    }//GEN-LAST:event_ManageActionPerformed

    private void AddRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRemoveActionPerformed
        // TODO add your handling code here:
        ADD_REMOVE addRemove = new ADD_REMOVE();
        setVisible(false);
        addRemove.setVisible(true);
    }//GEN-LAST:event_AddRemoveActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        SearchWindow searchWin = new SearchWindow();
        setVisible(false);
        searchWin.setVisible(true);
    }//GEN-LAST:event_SearchActionPerformed

    private void BorrowReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowReturnActionPerformed
        // TODO add your handling code here:
        BookIssueAndReturnWindow issueReturn = new BookIssueAndReturnWindow();
        setVisible(false);
        issueReturn.setVisible(true);
    }//GEN-LAST:event_BorrowReturnActionPerformed

    private void AvailBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvailBooksActionPerformed
        // TODO add your handling code here:
        AvailableBooks availBooks = new AvailableBooks();
        setVisible(false);
        availBooks.setVisible(true);
    }//GEN-LAST:event_AvailBooksActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        LOGIN login = new LOGIN();
        setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DASHBOARD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRemove;
    private javax.swing.JButton AvailBooks;
    private javax.swing.JButton BorrowReturn;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Manage;
    private javax.swing.JButton Search;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
