/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.librarymanagementsystem;

/**
 *
 * @author yan
 */
public class SearchInformation extends javax.swing.JFrame {

    /**
     * Creates new form BookBorrowedWindow
     */
    public SearchInformation(String title, String author, String bookNumber, String category, String availability) {
        initComponents();
        //String title, String author, String bookNumber, String category
        //labels wait lang
        titleLabel.setText(title);
        authorLabel.setText(author);
        bookNumberLabel.setText(bookNumber);
        categoryLabel.setText(category);
        availabilityLabel.setText(availability);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        bookNumberLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        availabilityLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dark_Back.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 200, 80));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 280, 30));

        authorLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        authorLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(authorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 280, 30));

        bookNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bookNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(bookNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 280, 30));

        categoryLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        categoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(categoryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 280, 30));

        availabilityLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        availabilityLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(availabilityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 280, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        SearchWindow search = new SearchWindow();
        setVisible(false);
        search.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SearchInformation("Sample Title", "Sample Author", "12345", "Fiction").setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    private javax.swing.JLabel availabilityLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bookNumberLabel;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
